// <auto-generated />
namespace ProEventApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Tags_added_to_appevent1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Tags_added_to_appevent1));
        
        string IMigrationMetadata.Id
        {
            get { return "201805080835286_Tags_added_to_appevent1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
