// <auto-generated />
namespace ProEventApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class eventComment_Who_added : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(eventComment_Who_added));
        
        string IMigrationMetadata.Id
        {
            get { return "201804090746171_eventComment_Who_added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
