// <auto-generated />
namespace ProEventApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Person_Profiledrop : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Person_Profiledrop));
        
        string IMigrationMetadata.Id
        {
            get { return "201801301341284_Person_Profile-drop"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
