// <auto-generated />
namespace ProEventApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class validation_added_to_Professional : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(validation_added_to_Professional));
        
        string IMigrationMetadata.Id
        {
            get { return "201802060741326_validation_added_to_Professional"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
