// <auto-generated />
namespace ProEventApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class city_state_addedToDb : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(city_state_addedToDb));
        
        string IMigrationMetadata.Id
        {
            get { return "201801191111540_city_state_addedToDb"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
