// <auto-generated />
namespace ProEventApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class eventFk_to_eventPro : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(eventFk_to_eventPro));
        
        string IMigrationMetadata.Id
        {
            get { return "201801230651309_eventFk_to_eventPro"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
