// <auto-generated />
namespace ProEventApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Profile_Image_ProfileImage_ProfileFkToPerson : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Profile_Image_ProfileImage_ProfileFkToPerson));
        
        string IMigrationMetadata.Id
        {
            get { return "201801201222525_Profile_Image_ProfileImage_ProfileFkToPerson"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
