// <auto-generated />
namespace ProEventApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Person_Professional_AppUser_addedToDb : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Person_Professional_AppUser_addedToDb));
        
        string IMigrationMetadata.Id
        {
            get { return "201801180732377_Person_Professional_AppUser_addedToDb"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
