// <auto-generated />
namespace ProEventApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class done_added_to_EventPro : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(done_added_to_EventPro));
        
        string IMigrationMetadata.Id
        {
            get { return "201804130729552_done_added_to_EventPro"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
