// <auto-generated />
namespace ProEventApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AppEvent_added_City_street_and_houseNumber : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AppEvent_added_City_street_and_houseNumber));
        
        string IMigrationMetadata.Id
        {
            get { return "201801250930010_AppEvent_added_City_street_and_houseNumber"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
