// <auto-generated />
namespace ProEventApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class image_added_comment_whoAdded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(image_added_comment_whoAdded));
        
        string IMigrationMetadata.Id
        {
            get { return "201803190809001_image_added_comment_whoAdded"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
