// <auto-generated />
namespace ProEventApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class CityFk_to_Person : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CityFk_to_Person));
        
        string IMigrationMetadata.Id
        {
            get { return "201801201219143_CityFk_to_Person"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
