// <auto-generated />
namespace ProEventApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ads_added_to_Models : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ads_added_to_Models));
        
        string IMigrationMetadata.Id
        {
            get { return "201805071047231_ads_added_to_Models"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
