// <auto-generated />
namespace ProEventApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class category_profession_added_toDb : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(category_profession_added_toDb));
        
        string IMigrationMetadata.Id
        {
            get { return "201801191118099_category_profession_added_toDb"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
