// <auto-generated />
namespace ProEventApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class date_added_to_AppEvent : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(date_added_to_AppEvent));
        
        string IMigrationMetadata.Id
        {
            get { return "201803201218391_date_added_to_AppEvent"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
