// <auto-generated />
namespace ProEventApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AppEventComment_OneToMany : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AppEventComment_OneToMany));
        
        string IMigrationMetadata.Id
        {
            get { return "201804110559503_AppEvent-Comment_OneToMany"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
