// <auto-generated />
namespace ProEventApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Rola_Added_To_EventProfessional : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Rola_Added_To_EventProfessional));
        
        string IMigrationMetadata.Id
        {
            get { return "201802091007578_Rola_Added_To_EventProfessional"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
