// <auto-generated />
namespace ProEventApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class eventID_changedTo_AppEventId_IN_EventImages : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(eventID_changedTo_AppEventId_IN_EventImages));
        
        string IMigrationMetadata.Id
        {
            get { return "201801251127518_eventID_changedTo_AppEventId_IN_EventImages"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
