// <auto-generated />
namespace ProEventApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddressFk_added_to_AppEvent_Person : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddressFk_added_to_AppEvent_Person));
        
        string IMigrationMetadata.Id
        {
            get { return "201801250840551_AddressFk_added_to_AppEvent_Person"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
