// <auto-generated />
namespace ProEventApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class EventPro_Stars_changed_to_Importance : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EventPro_Stars_changed_to_Importance));
        
        string IMigrationMetadata.Id
        {
            get { return "201804111123500_EventPro_Stars_changed_to_Importance"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
