// <auto-generated />
namespace ProEventApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AppUser_StringIDOfCurrentUser : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AppUser_StringIDOfCurrentUser));
        
        string IMigrationMetadata.Id
        {
            get { return "201802011314589_AppUser_StringIDOfCurrentUser"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
