// <auto-generated />
namespace ProEventApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Address_deletedFrom_AppEvent : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Address_deletedFrom_AppEvent));
        
        string IMigrationMetadata.Id
        {
            get { return "201801250927224_Address_deletedFrom_AppEvent"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
